### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/cloudfour.com-patterns#1580]
@dromo77 [reported a problem](https://cloudfour.slack.com/archives/C04AEEVK2/p1636656499022400) with running tests on her branch:

![Screen Shot 2021-11-11 at 10 47 19 AM](https://user-images.githubusercontent.com/257309/141372553-1aef1a2d-410a-4881-a821-3766a5736201.png)

I checked out `v-next` to validate that tests were passing there, and ran into trouble as well:

```
$ npm test

> @cloudfour/patterns@4.3.0 test /Users/scott/Sites/cloudfour.com-patterns
> jest

 FAIL  src/components/comment/comment.test.ts (6.38 s)
  ● reply form can be opened and closed

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      12 |   `);
      13 |
    > 14 | test(
         | ^
      15 |   'reply form can be opened and closed',
      16 |   withBrowser(async ({ utils, screen, user }) => {
      17 |     await utils.injectHTML(

      at Object.<anonymous> (src/components/comment/comment.test.ts:14:1)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/components/comment/comment.test.ts.

      at node_modules/puppeteer/src/common/BrowserConnector.ts:54:8
      at getWebSocketTransportClass (node_modules/puppeteer/src/common/BrowserConnector.ts:54:8)
      at Object.connectToBrowser (node_modules/puppeteer/src/common/BrowserConnector.ts:91:28)
 FAIL  src/components/input/elastic-textarea.test.ts (11.251 s)
  ● Resizes correctly with no rows attribute

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      14 |   );
      15 |
    > 16 | test(
         | ^
      17 |   'Resizes correctly with no rows attribute',
      18 |   withBrowser(async ({ utils, screen, user }) => {
      19 |     await utils.injectHTML(

      at Object.<anonymous> (src/components/input/elastic-textarea.test.ts:16:1)

  ● Allows you to override the minimum number of rows

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      51 | );
      52 |
    > 53 | test(
         | ^
      54 |   'Allows you to override the minimum number of rows',
      55 |   withBrowser(async ({ utils, screen, user }) => {
      56 |     await utils.injectHTML(

      at Object.<anonymous> (src/components/input/elastic-textarea.test.ts:53:1)

 FAIL  src/components/sky-nav/sky-nav.test.ts (11.304 s)
  ● can be opened on small screens

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      16 |   );
      17 |
    > 18 | test(
         | ^
      19 |   'can be opened on small screens',
      20 |   withBrowser({ device: iPhone }, async ({ utils, screen, user }) => {
      21 |     await utils.injectHTML(await skyNavMarkup({ includeMainDemo: true, menu }));

      at Object.<anonymous> (src/components/sky-nav/sky-nav.test.ts:18:1)

  ● is expanded on large screens

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      38 | );
      39 |
    > 40 | test(
         | ^
      41 |   'is expanded on large screens',
      42 |   withBrowser(async ({ utils, screen }) => {
      43 |     await utils.injectHTML(await skyNavMarkup({ includeMainDemo: true, menu }));

      at Object.<anonymous> (src/components/sky-nav/sky-nav.test.ts:40:1)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/components/input/elastic-textarea.test.ts.

      at node_modules/puppeteer/src/common/BrowserConnector.ts:54:8
      at getWebSocketTransportClass (node_modules/puppeteer/src/common/BrowserConnector.ts:54:8)
      at Object.connectToBrowser (node_modules/puppeteer/src/common/BrowserConnector.ts:91:28)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/components/sky-nav/sky-nav.test.ts.

      at node_modules/puppeteer/src/common/BrowserConnector.ts:54:8
      at getWebSocketTransportClass (node_modules/puppeteer/src/common/BrowserConnector.ts:54:8)
      at Object.connectToBrowser (node_modules/puppeteer/src/common/BrowserConnector.ts:91:28)
 FAIL  src/components/button-swap/button-swap.test.ts (21.222 s)
  ● Initial state

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      28 |   );
      29 |
    > 30 | test(
         | ^
      31 |   'Initial state',
      32 |   withBrowser(async ({ utils, screen }) => {
      33 |     await utils.injectHTML(await componentMarkup());

      at Object.<anonymous> (src/components/button-swap/button-swap.test.ts:30:1)

  ● Swap UI state when clicked

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      56 | );
      57 |
    > 58 | test(
         | ^
      59 |   'Swap UI state when clicked',
      60 |   withBrowser(async ({ utils, screen, user }) => {
      61 |     await utils.injectHTML(await componentMarkup());

      at Object.<anonymous> (src/components/button-swap/button-swap.test.ts:58:1)

  ● Set custom messages and labels

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      115 | );
      116 |
    > 117 | test(
          | ^
      118 |   'Set custom messages and labels',
      119 |   withBrowser(async ({ utils, screen, user }) => {
      120 |     await utils.injectHTML(

      at Object.<anonymous> (src/components/button-swap/button-swap.test.ts:117:1)

[browser] Error: Failed to load resource: net::ERR_CONNECTION_REFUSED
    at http://localhost:50688/@pleasantest/jest-dom
[browser] Error: Failed to load resource: net::ERR_CONNECTION_REFUSED
    at http://localhost:50688/@pleasantest/jest-dom
Test Suites: 4 failed, 4 total
Tests:       8 failed, 1 passed, 9 total
Snapshots:   0 total
Time:        21.721 s, estimated 22 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by calebeby** [comment]
@spaceninja I think the issue you are seeing and the one @dromo77 is seeing are separate issues.

The one you are seeing is usually because sometimes puppeteer takes a while to start a browser. Usually, if you run the tests a second time, it will launch the browsers fast enough for Jest to not kill the tests. Let me know if that happens to you or not. We can also increase the timeout to 10 or 15 seconds to avoid this.

**Comment by spaceninja** [comment]
Confirmed the tests succeeded on successive runs after an initial failure.
